---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Mushborg repository:
        - abbr: GH
          href: https://github.com/glitched0xff/MushBorgApp
